name: CI of the Project

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test if it's working
    runs-on: ubuntu-latest

    steps:
      - name: hello
        run: echo "hello world!"
      - env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
