name: CI of the Project

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build 
    runs-on: ubuntu-latest

    steps:
      - name: setup jdk 17
        uses: actions/setup-java@v3

      - name: Build with Maven
        run: mvn clean package
