name: Java Maven Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Increment Patch Version
        run: mvn build-helper:parse-version versions:set -DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion} versions:commit
      
      - name: Test with Maven
        run: mvn test
      
      - name: Build with Maven
        run: mvn package
      
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: "target/*.jar"
          
      - name: Cleanup
        if: always()
        run: |
          rm -rf target/surefire-reports
