name: Java Maven Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Test with Maven
        run: mvn test
      
      - name: Build with Maven
        run: mvn package

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v3
      
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: "target/*.jar"

      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
          
      - name: Cleanup
        if: always()
        run: |
          rm -rf target/surefire-reports
